### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by Chrysostomus** [Manjaro-Pek/pacli#11]
There has been a suggestion in aur to rename pacli to pacmenu. What do you think about the matter? Personally I think there is some merit to suggestion, but I'm largely indifferent towards the matter. I would imagine there was some logic behind the original naming though.

**Comment by neton-bricio** [comment]
pacli It has a meaning.

pac = pacman
cli = comand line solution script

That makes perfect sense. So change the project name is out

**Comment by Chrysostomus** [comment]
Excellent, so we have a solution to this issue! :-)

**Comment by excalibur1234** [comment]
i also like pacli's current name!
