### ISSUE TITLE
combine options "package info" and "installed package info"

### ISSUE THREAD

**Issue by excalibur1234** [Manjaro-Pek/pacli#13]
either combine these 2 options into 1 or remove them both.

the most important options are imho:
- package name and other packages with a similar name
- package description
- installation size of packages including all dependencies
- dependencies
  these pieces of information can be obtained by "install package" and "dependency tree".

what do you prefer? remove them or combine them into 1 option?

**Comment by Chrysostomus** [comment]
I would combine them into one. I have been looking into how to combine the output list in a sane way. After sorting that we could use option recommended by papajoke.

**Comment by Chrysostomus** [comment]
Main thing I'm concerned with is whether it sees local custom packages. Using input list of option 5 gives all repo and aur packages. This would cover 97% of use cases, but it will not show any custom packages you made yourself, unless you uploade them to aur.
