### ISSUE TITLE
include option to change /etc/pacman.conf ?

### ISSUE THREAD

**Issue by excalibur1234** [Manjaro-Pek/pacli#14]
after downgrading a package, the user gets asked whether he/she wants to ignore all future updates of the downgraded package. until now, there is no easy way included in pacli to revert such a change.
should we include a red option "sudo nano /etc/pacman.conf"?

pros: expert users have more options available.

cons: 
- too complicated for beginner level users. 
- we will have 5 red options --> looks bad
- we will have an odd amount of options in the second part/block --> looks bad
- we will have too many options in the second part/block --> too many options are confusing.

**Comment by Chrysostomus** [comment]
I think it would be a good option to have in general. if we ibclude upkeep option and replace some stuff with it, then there would be more room for it. Maybe no need to put it in red area? Or we could put fix errors there too to keep things symmetrical.

Would it make sense to also include options to edit yaourtrc and makepkg.conf too? In the aur section.
