### ISSUE TITLE
should option 2 also update the system?

### ISSUE THREAD

**Issue by excalibur1234** [Manjaro-Pek/pacli#24]
option 2 is called "clean system".
either, we have to call it "update + clean system" or we have to remove the updating code in it.

i would prefer the latter.
what is your opinion?

**Comment by Chrysostomus** [comment]
Well, that was originally the 'Upkeep' option, that was intended to be one click action to update and clean the system. I just adopted papajokers naming. Seemed... cleaner. 

I'm fine with it being changed.

**Comment by excalibur1234** [comment]
i am gonna change it.
