### ISSUE TITLE
mark option 24 as red?

### ISSUE THREAD

**Issue by excalibur1234** [Manjaro-Pek/pacli#25]
how dangerous is it to edit this file?
can it break your system?

if yes, it should be marked red.

**Comment by Chrysostomus** [comment]
Nah, it is much safer than editing pacman.conf. it is user level config.

**Comment by Chrysostomus** [comment]
It effects stuff like colors, whether or not to edit pkgbuild, and where to export built packages. At worst, messing this file should only prevent building packages that require editing before building.

**Comment by excalibur1234** [comment]
ok. lets keep it the way it is.
