### ISSUE TITLE
error in option 220

### ISSUE THREAD

**Issue by excalibur1234** [Manjaro-Pek/pacli#26]
when i try to install pacli from this repository with option 220, i receive the following error:
`
-> Klone das pacli git Repo...
fatal: Zielpfad '/tmp/pacli-git/pacli' existiert bereits und ist kein leeres Verzeichnis.
==> FEHLER: Fehler beim Download des pacli git Repos
    Breche ab...
`
what am i doing wrong?

p.s.: even, when i try to clone the git repo manually and do "makepkg -scfi", i receive the same error message.

**Comment by Chrysostomus** [comment]
Try again after reboot or delete /tmp/pacli-git/pacli first.

**Comment by excalibur1234** [comment]
i delete it first (in pacli's code, it also gets deleted first).

but i can test this again tonight.

**Comment by papajoker** [comment]
sorry typo error #29

**Comment by excalibur1234** [comment]
i have not tested the new code, but it appears this was fixed with #28

**Comment by papajoker** [comment]
sorry, no
I now understands your problem, it's specific to repo pacli
makepkg create 3 directories ("src", "pkg" ans "name-git-repo") with pacli we have a file of the same name so PKGBUILD not afraid to run

in my branch developer, i remove this 3 files/directories and its ok. And i have add the choise of the branch; tested in my fork its ok
