### ISSUE TITLE
pacli slow again?

### ISSUE THREAD

**Issue by excalibur1234** [Manjaro-Pek/pacli#30]
i can actually see now how pacli's home screen gets drawn in my terminal.

is it just me or has pacli's home screen become really slow again with pull request #28 ?

**Comment by papajoker** [comment]
currently I'm working on another very different branch:
- Sizes calculated only once and not in the loop as now, therefore faster ...
- The size is calculated by the largest item menus, so depending on the translation (the translation currently truncated)
- The size is re-calculated for the prompt on the Home screen
- Home Prompt updated automatically (no need to rewrite the translation files: 0..à of 25)
- Prompt and title are automatically centered if smaller than the frame
- Menu items are quick and some close for internationalization (.po file)
- All function non-directly links at yaourt or pacman are moved in an external file .sh for clarify code.
- menu in array
- normalize promts for easy translation
- normalise input fzf for easy translation and option to cancel with ESC or bad enter
- different ouput if pactree -r is empty
- new page informations (branch, repo, repo update...) [100]
- new page manage .pacnews [111]
- hidden items menu >49
- main menu zfz - touch "m"/"esc" - items menu >49 - Add option paclirc for validate ?
- palirc, 2 new options : mainmenu fzf et "Cancel" item in select box

To create a translation test file (editable with poedit) in "locale" subfolder use scripts in /locale/ and for a local test :

```
 msgfmt -o locale/de.mo locale/de.po
 #install (make by PKGBUILD)
 sudo cp locale/de.mo /usr/share/locale/de/LC_MESSAGES/pacli.mo
 # test
 LANG=de ./pacli
```

Branch: https://github.com/papajoker/pacli/tree/develop

**Comment by excalibur1234** [comment]
this sounds great. take all the time you need.

**Comment by excalibur1234** [comment]
this issue is solved, but i would like to keep it open until papajoker finishes his branch.

**Comment by papajoker** [comment]
voila,

I think it's very close to a final version (in terms of functionality)
every detail in the above post
It is possible that some functions will not work well (2 ...) I have not tested all for exemple red.

For the translation, he must miss some string in pacli-tools.sh to convert with gettext()

Branch: https://github.com/papajoker/pacli/tree/develop

-and beginning to support several helpers: yaourt or pacaur

**Comment by excalibur1234** [comment]
the new version is pretty fast...
