### ISSUE TITLE
AUR PKGBUILD version

### ISSUE THREAD

**Issue by papajoker** [Manjaro-Pek/pacli#32]
@Chrysostomus 
small problem with versions aur

in PKGBUILD : pkgver=0.7
in .[SRCINFO](https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=pacli) : pkgver = 0.6
and downloaded 0.8 ...  ?? not git tag and not in code for found the real version

**Comment by Chrysostomus** [comment]
Okay, I need to update it.

**Comment by Chrysostomus** [comment]
I'm having some trouble updating it. I keep getting 403 error.

**Comment by Chrysostomus** [comment]
Okay, fixed.

**Comment by papajoker** [comment]
thank you for the archer, but without help file installed by the PKGBUILD the program will crash every request for help.

**Comment by excalibur1234** [comment]
i have also installed pacli from the aur a couple of minutes ago: the help page does not get displayed. it seems it is missing somehow.

**Comment by papajoker** [comment]
yes add in package() function

```
install -Dm544 "$srcdir/$pkgname/pacli.help" "$pkgdir/usr/share/doc/pacli/help"
```

**Comment by Chrysostomus** [comment]
Whoops. Got it, thanks!

**Comment by Chrysostomus** [comment]
Done
