### ISSUE TITLE
pactree 7 and AUR

### ISSUE THREAD

**Issue by papajoker** [Manjaro-Pek/pacli#36]
in list , It's missing AUR packages
for make a `pactree -c "aur-package"` without option `-s`

**Comment by excalibur1234** [comment]
thanks for the tip! you are right.

i just fixed it: https://github.com/Manjaro-Pek/pacli/commit/7234b6dcd8c275c70ac3ba300d03d19810c72258

**Comment by excalibur1234** [comment]
i just thought about it again:
- with option -s, you can display the dependency tree of all packages from manjaro repositories, even if they are not installed on your system.
- without option -s, you can display the dependency tree of installed AUR packages on your system, but you cannot display the dependency tree of all packages from manjaro repositories.

what is more important?

**Comment by papajoker** [comment]
test if local, `pactree -cs package` only if not local: 

```
pkg=$(pacman -Slq | fzf-tmux -e --reverse --prompt='Select a package >') # NOT  -Slq !
option='s'
(yaourt -Qs "^${pkg}$" | head -n 1 | grep "^local" &>/dev/null) && option=''  # AUR
pactree -c${option} "$pkg"
unset option pkg
```

**Comment by excalibur1234** [comment]
i have just seen that you already edited option 7 and 8 heavily in your branch: https://github.com/papajoker/pacli/commit/6e2b2e23d47d3e5b748eb30d13cc22edb1a53028

i do not like to edit these options while you do something else.
let's wait until you have finished your branch. then, we can talk about further improvements.
