### ISSUE TITLE
extra code in options 1, 2, 3

### ISSUE THREAD

**Issue by excalibur1234** [Manjaro-Pek/pacli#38]
this code line is in option 1, 2, and 3:
`
[ -f "${pacli_desc}" ] && cat "${pacli_desc}"
`
it looks like it is displays a package description at the bottom of each option.
why is this code line there?
does it do something useful?

**Comment by papajoker** [comment]
this code display file generated by hook, this function is now optional and set in paclirc file ;  branch developer
