### ISSUE TITLE
when i choose option 17 or 18, i see help text for option 15

### ISSUE THREAD

**Issue by excalibur1234** [Manjaro-Pek/pacli#43]

**Comment by cimarronline** [comment]
Yes, the code in pacli for option 17 and 18 (lines 486 and 496) reads "help_text 15". If the 15 is changed to 17/18 then it works properly.

**Comment by neton-bricio** [comment]
I could not fully understand the problem!

**Comment by excalibur1234** [comment]
[this line](https://github.com/Manjaro-Pek/pacli/blob/master/pacli#L486) should be corrected to
`help_text 17 "${PARAMS['helpred']}" || continue`
(note the "17" here!)

the same has to be corrected in line 496.

but i do not do any development for pacli anymore, because pacui has a lot of improvements i really like: https://github.com/excalibur1234/pacui

if you are looking for a (slightly) updated version of pacli, please look here: https://github.com/papajoker/pacli/tree/commands

**Comment by cimarronline** [comment]
Yes, thanks. Looks like papajoker's version has the same problem...

**Comment by papajoker** [comment]
fixed https://github.com/Manjaro-Pek/pacli/commit/1bab38fd05feeaf711e35d03a080959aa60f16a2 , after for update PKGBUILD is excalibur1234 ?

**Comment by excalibur1234** [comment]
> after for update PKGBUILD is excalibur1234 ?

yes. 
this update (https://github.com/Manjaro-Pek/pacli/commit/0899b656157d75f53e0a9fffd9a56e5513b20faf) was for pacli-simple. but pacli-simple has been renamed to pacui. therefore, this update is no longer necessary.

you can merge your changes and overwrite that update, if you want.
