### ISSUE TITLE
Can't scroll DOWN  in lists

### ISSUE THREAD

**Issue by freed00m** [Manjaro-Pek/pacli#49]
My mousewheel scrolls ok with urxvt terminals.

The problem is, the app in option (4) or (5) displays list of packages, where it's posible to use mouse for navigation.

However I can scroll only in one direction and that's UP. Scrolling DOWN doesn't move the carret.

**Comment by Chrysostomus** [comment]
I'll look into the matter. Btw, just checking because some people have missed it... You do know that the view there is a search field? You can filter apps by typing parts of their names, much faster than scrolling.

**Comment by freed00m** [comment]
@Chrysostomus Thanks, yes I know that, I just wanted to scroll through my list to spot on things I might remove and noticed that I can only go UP. :)

**Comment by Chrysostomus** [comment]
Good. And that is quite sensible use case. I'll experiment a bit with different terminals.

**Comment by Chrysostomus** [comment]
I can reliably reproduce the issue. Seems like a bug in fzf. Trying now if updating fzf helps...

**Comment by Chrysostomus** [comment]
Nope, the issue is still present in fzf-git. I suggest opening an issue here: https://github.com/junegunn/fzf

**Comment by excalibur1234** [comment]
i am using qterminal and the scroll with mouse wheel does not work in UP or DOWN direction.

i agree it should be an issue of fzf.
but i have never pictured pacli as a mouse centric application. i always use the ARROW keys or PageUp/PageDown keys to scroll the list. but most of the time i use the fuzzy search.
how do you select multiple packages by using the mouse?

**Comment by Chrysostomus** [comment]
Shift + click

**Comment by Chrysostomus** [comment]
While it is not an essential feature, it would be nice if it worked. But we can't fix it, it's up to upstream.
