### ISSUE TITLE
Implement locale integration (internationalizing)

### ISSUE THREAD

**Issue by neton-bricio** [Manjaro-Pek/pacli#5]
Next step to integrate with the system locale.

Any doubt consult this article: http://docs.slackware.com/howtos:misc:internationalization_and_localization_of_shell_scripts 

http://docs.slackware.com/howtos:misc:internationalization_and_localization_of_shell_scripts

**Comment by papajoker** [comment]
version "developer is ok"
- It takes a lot of source code change: 
  
  ```
  echo "Enter a number ..."   # to 
  echo "$(gettext 'Enter a number ...')"
  ```
  
  -make .po files, merge, use an external site for translators
  view : https://github.com/rmarquis/pacaur/blob/master/po/HOWTO

**Comment by neton-bricio** [comment]
i work

**Comment by papajoker** [comment]
i copy scripts from pamac in /locale/ for easy create .pot from sources (.sh) ; in my pull request #41  , wait the merge in pek repo...
i have also a waiting push request https://github.com/papajoker/pacli/pull/1 for pl

**Comment by excalibur1234** [comment]
i have not tested this yet, because i use the english version of pacli, but it should work now.

if you experience any problems create a new issue.
