### ISSUE TITLE
Cron script to check for updates

### ISSUE THREAD

**Issue by neton-bricio** [Manjaro-Pek/pacli#9]
Create a shell script to check for updates. Set to auto run via Cron YXY hours.

Using cron to beneft OpenRC user.

**Comment by Chrysostomus** [comment]
I have update checking script available, part of lemonpanel package. Would this type of thing serve? https://github.com/Chrysostomus/lemonpanel/blob/master/bin/update-notifier

link is no longer working. new link: 
https://github.com/Chrysostomus/update-notifier

**Comment by pekman1** [comment]
It seems a good starting point. I will run a round of tests. It checks for updates and notifies you? That's right?

**Comment by neton-bricio** [comment]
Well it looks perfect. I will work to internationalization and climb everything back to Git Hub later.

**Comment by Chrysostomus** [comment]
Ok. I'll make it into a separate package and make pacli and lemonpanel depend on it.

**Comment by excalibur1234** [comment]
now, the documentation and github page need to be updated with this cron script as dependency.

a short description how to use/activate the cron script would be nice, too.

**Comment by Chrysostomus** [comment]
That would make sense. However, I don't use cron, so I'm ill equipped to advice on the matter.

**Comment by excalibur1234** [comment]
i use cron to regularly check for updates. but i use it in a non-standard way like that:

create ~/.crontab file and enter:
        \* */7 \* \* \* yaourt -Sy
execute the following command once (and every time the content of the ~/.crontab file changed):
        sudo crontab ~/.crontab -u root

i am reluctant to recommend this way to other users. i have heard of people, who have simply added a new file to /etc/cron.daily/ and manjaro automatically took care of running their script once a day. i have tried that method but always failed.

**Comment by Chrysostomus** [comment]
Yeah, synchronizing database as cronjob is risky if you don't know what you are doing. But update-notifier would work nicely if ran like that :-). I did not know one could have crontab in $HOME, thanks!

**Comment by excalibur1234** [comment]
i just called that file .crontab but you can call it anyway you want. i think you can also place it anywhere you want.

the risky part about it is "-u root" this means that the file content of .crontab is run every 7 hours with root privileges. but everybody can change the file content of .crontab, because it is not located in my root directory.

**Comment by excalibur1234** [comment]
i have just added update-notifier as optional dependency: 21007fda42185593150e3c2efff13fe702e9c475
also, i have added detailed descriptions how to use it: https://github.com/Chrysostomus/update-notifier/pull/2

this should conclude this issue.
